apiVersion: v1
kind: Pod
metadata:
  name: node-debugger
spec:
  nodeName: node69
  hostPID: true
  hostNetwork: true
  hostIPC: true
  containers:
  - name: debug-shell
    image: ubuntu
    stdin: true
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
      