#!/bin/sh

set -e

./setenv

talhelper validate talconfig
rm -Rf clusterconfig
talhelper genconfig

talhelper gencommand apply --extra-flags "--dry-run --insecure"
#talhelper gencommand apply
#talhelper gencommand upgrade
#talhelper gencommand upgrade-k8s


