clusterName: ceph-k8s
talosVersion: v1.9.2
kubernetesVersion: v1.32.0
endpoint: https://control.ceph.impl.nl:6443
allowSchedulingOnControlPlanes: true
additionalMachineCertSans:
  - control.ceph.impl.nl
  - jasmine.odee.net
  - 127.0.0.1
additionalApiServerCertSans:
  - jasmine.odee.net
  - 127.0.0.1
controlPlane:
  nameservers:
    - 1.0.0.1
    - 8.8.4.4
    - 8.8.8.8
worker:
  nameservers:
    - 1.0.0.1
    - 8.8.4.4
    - 8.8.8.8
nodes:
  - hostname: node65
    ipAddress: 192.168.1.65
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node66
    ipAddress: 192.168.1.66
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node67
    ipAddress: 192.168.1.67
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node68
    ipAddress: 192.168.1.68
    controlPlane: false
    installDisk: /dev/mmcblk0
