clusterName: ceph-k8s
talosVersion: v1.6.1
kubernetesVersion: v1.29.0
endpoint: https://control.ceph.impl.nl:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - control.ceph.impl.nl
  - jasmine.odee.net
  - 127.0.0.1
additionalApiServerCertSans:
  - control.ceph.impl.nl
  - jasmine.odee.net
  - 127.0.0.1
nodes:
  - hostname: node60
    ipAddress: 192.168.1.60
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node61
    ipAddress: 192.168.1.61
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node62
    ipAddress: 192.168.1.62
    controlPlane: true
    installDisk: /dev/mmcblk0
  - hostname: node63
    ipAddress: 192.168.1.63
    controlPlane: false
    installDisk: /dev/mmcblk0
  - hostname: node64
    ipAddress: 192.168.1.64
    controlPlane: false
    installDisk: /dev/mmcblk0
  - hostname: node65
    ipAddress: 192.168.1.65
    controlPlane: false
    installDisk: /dev/mmcblk0
  

controlPlane:
  patches:
    - |-
      machine:
        network:
          nameservers:
            - 8.8.4.4
            - 1.1.1.1
            - 8.8.8.8
    - |-
      cluster:
        allowSchedulingOnMasters: true
