apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 85.2.0
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          assertNoLeakedSecrets: false
          adminPassword: killer
          defaultDashboardsEnabled: false
          grafana.ini:
            analytics:
              check_for_updates: false
              reporting_enabled: false
            users:
              home_page: /dashboards
            server:
              root_url: https://grafana.ceph.impl.nl
            # auth:
            #   disable_login_form: true
            #   disable_signout_menu: true
            security:
              disable_brute_force_login_protection: true
              allow_embedding: true

            auth.generic_oauth:
              name: Keycloak
              enabled: true
              allow_sign_up: true
              client_id: main
              scopes: openid profile email
              email_attribute_path: email
              login_attribute_path: username
              name_attribute_path: full_name
              auth_url: https://auth.impl.nl/realms/impl/protocol/openid-connect/auth
              token_url: https://auth.impl.nl/realms/impl/protocol/openid-connect/token
              api_url: https://auth.impl.nl/realms/impl/protocol/openid-connect/userinfo
              use_pkce: true
              use_refresh_token: true

          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress.ceph.impl.nl
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              cert-manager.io/cluster-issuer: letsencrypt-production
            path: /
            pathType: Prefix
            extraPaths: []
            hosts:
              - grafana.ceph.impl.nl
            tls:
              - secretName: grafana.ceph.impl.nl
                hosts:
                  - grafana.ceph.impl.nl
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false

        prometheus-node-exporter:
          prometheus:
            monitor:
              attachMetadata:
                node: true
              relabelings:
                - action: replace
                  sourceLabels:
                    - __meta_kubernetes_node_name
                  targetLabel: node
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
