apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.1.0
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          adminPassword: killer
          grafana.ini:
            analytics:
              check_for_updates: false
              reporting_enabled: false
            server:
              root_url: https://grafana.ceph.impl.nl
            security:
              disable_brute_force_login_protection: true
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            pathType: Prefix
            extraPaths: []
            hosts:
              - grafana.ceph.impl.nl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
