apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 71.1.0
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          adminPassword: killer
          defaultDashboardsEnabled: false
          grafana.ini:
            analytics:
              check_for_updates: false
              reporting_enabled: false
            server:
              root_url: https://grafana.ceph.impl.nl
            security:
              disable_brute_force_login_protection: true
              allow_embedding: true
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress.ceph.impl.nl
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              cert-manager.io/cluster-issuer: letsencrypt-production
            path: /
            pathType: Prefix
            extraPaths: []
            hosts:
              - grafana.ceph.impl.nl
            tls:
              - secretName: grafana.ceph.impl.nl
                hosts:
                  - grafana.ceph.impl.nl
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'grafana-dashboards-ceph'
                orgId: 1
                folder: 'Ceph'
                type: file
                disableDeletion: true
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/grafana-dashboards-ceph
          dashboards:
            grafana-dashboards-ceph:
              ceph-cluster-advanced:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/ceph-cluster-advanced.json
                token: ''
              ceph-cluster:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/ceph-cluster.json
                token: ''
              cephfs-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/cephfs-overview.json
                token: ''
              host-details:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/host-details.json
                token: ''
              hosts-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/hosts-overview.json
                token: ''
              multi-cluster-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/multi-cluster-overview.json
                token: ''
              osd-device-details:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/osd-device-details.json
                token: ''
              osds-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/osds-overview.json
                token: ''
              pool-detail:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/pool-detail.json
                token: ''
              pool-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/pool-overview.json
                token: ''
              radosgw-detail:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/radosgw-detail.json
                token: ''
              radosgw-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/radosgw-overview.json
                token: ''
              radosgw-sync-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/radosgw-sync-overview.json
                token: ''
              rbd-details:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/rbd-details.json
                token: ''
              rbd-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/rbd-overview.json
                token: ''
              rgw-s3-analytics:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/rgw-s3-analytics.json
                token: ''
              smb-overview:
                url: https://raw.githubusercontent.com/ceph/ceph/refs/heads/main/monitoring/ceph-mixin/dashboards_out/smb-overview.json
                token: ''
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false

        prometheus-node-exporter:
          prometheus:
            monitor:
              attachMetadata:
                node: true
              relabelings:
                - action: replace
                  sourceLabels:
                    - __meta_kubernetes_node_name
                  targetLabel: node
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
