currentNamespaceOnly: true

#monitoring:
#  enabled: true

csi:
  enableGrpcMetrics: false
  enableLiveness: true
  enableCephfsDriver: false
  enableCephfsSnapshotter: false
  enableNFSSnapshotter: false
  enableRBDSnapshotter: false
  readAffinity:
    enabled: true
  enableDiscoveryDaemon: false

tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"


# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi
