apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.16.3
    helm:
      valuesObject:

        currentNamespaceOnly: false

        csi:
          enableRbdDriver: false
          enableLiveness: true
          enableCephfsDriver: false
          enableCephfsSnapshotter: false
          enableNFSSnapshotter: false
          enableRBDSnapshotter: false
          readAffinity:
            enabled: true
          serviceMonitor:
            enabled: true
            interval: 15s

        monitoring:
          enabled: true

        tolerations:
          - key: "node.kubernetes.io/unschedulable"
            operator: "Exists"
            effect: "NoSchedule"
          - key: node-role.kubernetes.io/control-plane
            operator: "Exists"
            effect: "NoSchedule"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
