# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: rook-ceph-operator
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: rook-ceph
#   project: default
#   source:
#     chart: rook-ceph
#     repoURL: https://charts.rook.io/release
#     targetRevision: v1.13.1
#     helm:
#       valuesObject:
#         currentNamespaceOnly: true

#         #monitoring:
#         #  enabled: true

#         csi:
#           enableGrpcMetrics: false
#           enableLiveness: true
#           enableCephfsDriver: false
#           enableCephfsSnapshotter: false
#           enableNFSSnapshotter: false
#           enableRBDSnapshotter: false
#           readAffinity:
#             enabled: true
#           enableDiscoveryDaemon: false

#         tolerations:
#           - key: "node.kubernetes.io/unschedulable"
#             operator: "Exists"
#             effect: "NoSchedule"
#           - key: node-role.kubernetes.io/control-plane
#             operator: "Exists"
#             effect: "NoSchedule"


#         # resources:
#         #   limits:
#         #     cpu: 500m
#         #     memory: 512Mi
#         #   requests:
#         #     cpu: 100m
#         #     memory: 128Mi

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - ServerSideApply=true
