apiVersion: v1
kind: Pod
metadata:
  name: wipe-rook62
spec:
  restartPolicy: Never
  nodeName: node62
  containers:
    - name: disk-wipe
      image: ubuntu
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        [
          "apt update; apt install fdisk gdisk parted udev -y; sgdisk --zap-all /dev/nvme0n1; dd if=/dev/zero bs=1M count=100 oflag=direct,dsync of=/dev/nvme0n1; wipefs -af /dev/nvme0n1; blkdiscard /dev/nvme0n1; partprobe /dev/nvme0n1",
        ]
