apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.5.7
    helm:
      valuesObject:
        dex:
          enabled: false
        repoServer:
          metrics:
            enabled: false
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
        server:
          metrics:
            enabled: false
          env:
            - name: SSL_CERT_DIR
              value: "/app/config/tls/"
          extraArgs:
            - --insecure
          config:
            repositories: |
              - type: helm
                name: argo-cd
                url: https://argoproj.github.io/argo-helm
          redis:
            metrics:
              enabled: false
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              external-dns.alpha.kubernetes.io/target: ingress.ceph.impl.nl
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              cert-manager.io/cluster-issuer: letsencrypt-production
            hostname: argocd.ceph.impl.nl
            tls: true
        applicationSet:
          metrics:
            enabled: false
        notifications:
          metrics:
            enabled: false
        controller:
          metrics:
            enabled: false
        configs:
          cm:
            admin.enabled: true
            application.resourceTrackingMethod: annotation+label
            url: http://argocd.ceph.impl.nl
          rbac:
            create: true
          params:
            application.namespaces: "*"
            server.insecure: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


