apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.3
    helm:
      valuesObject:
        controller:
          watchIngressWithoutClass: true

          # replicaCount: 3
          # minAvailable: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          service:
            annotations:
              metallb.universe.tf/address-pool: ipaddresspool-ceph-k8s
              metallb.universe.tf/loadBalancerIPs: 192.168.1.55
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
